### ISSUE TITLE
Black background in fullscreen mode when exporting html

### ISSUE THREAD

**Issue by PabloVD** [medialab/ipysigma#240]
I'm trying the [export html demo](https://github.com/medialab/ipysigma/blob/master/notebooks/Demo%20HTML%20Export.ipynb) without modifying these settings.
The html is correctly generated and renders successfully. However, when I push the button to enter into fullscreen mode, the background turns black as shown below, losing readability.
Is it a bug or there is any setting that I can turn on to avoid that?
Thanks in advance
![Captura de pantalla de 2024-10-14 15-33-44](https://github.com/user-attachments/assets/dba47dbc-aa11-4f4d-8708-9e9b75ff86e2)

**Comment by Yomguithereal** [comment]
You are right indeed. Let me check this out. I must have messed something up wrt the `background_color` kwarg.

**Comment by Yomguithereal** [comment]
Just released a version v0.24.3 that should take care of this issue. The default background for fullscreen in most browsers is black. I override the background color anyway but it seems latest Jupyter developments are tempering with said override so I made this override less "polite" :)

**Comment by PabloVD** [comment]
Thank you for taking care of that! Unfortunately, I upgraded to version 0.24.3 with pip --upgrade and I still have the same problem, in both Chrome and Firefox.
Maybe do I need to include any additional argument in `Sigma.write_html`?

**Comment by PabloVD** [comment]
Still not working in versoin 0.24.4, any possible solution for that?

**Comment by Yomguithereal** [comment]
So this is a weird bug. One workaround for now is to pass `background_color="rgb(255, 255, 255)"` to `write_html`. Will now investigate if my code is flawed or if `ipywidgets` is doing black magic on the static embeds.

**Comment by Yomguithereal** [comment]
So it's `ipywidgets` doing shitty magic suppressing CSS white background color against my will. I published a probable fix on v0.24.5. Can you report to tell me if this works?

**Comment by PabloVD** [comment]
Thanks for the update! Using the new version 0.24.5 by default does not fix the issue. However, including `background_color="rgb(255, 255, 255)"` as you mention fixed it. It would be nice if that option was by default, but it works for now. Many thanks!
